apiVersion: apps/v1
kind: Deployment
metadata:
  name: lattice-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: lattice-frontend
  template:
    metadata:
      labels:
        app: lattice-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lattice-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: lattice-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
