apiVersion: v1
kind: Secret
metadata:
  name: initial-admin-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.admin.username | b64enc | quote }}
  password: {{ .Values.admin.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.password | b64enc | quote }}
